name: contam_filter
owner: drevoz
description: Filter contaminant reads
long_description: Python script to remove contaminant reads of known origin based on alignment to two genomes - target and contaminant.
homepage_url: 
remote_repository_url: 
categories:
- SAM