name: region_dnacopy
owner: drevoz
description: Finds regions present on chromosomes
long_description: R script to find regions present on sequenced chromosomes based on read alignment to a reference genome.
homepage_url: https://github.com/drevoz/galaxy_dopseq/tree/master/tools/region_dnacopy
categories:
- Genomic Interval Operations
type: unrestricted